### ISSUE TITLE
some questions about free_seq's update in io.c

### ISSUE THREAD

**Issue by lb23333** [snu-csl/nvmevirt#51]
<img width="920" alt="捕获33" src="https://github.com/user-attachments/assets/2bd53f16-7ac3-4f4f-a640-7a0767c02458">
How should new nvmev_io_work be allocated when free_seq reaches queue depth? Why is there no update to free_seq in the __reclaim_completed_reqs function?

**Comment by beowulf** [comment]
1.  If io_work is depleted, it means there are too many outstanding requests. You'd throttle the rate or increase the size of workqueue.
2. free_req points to the next available io_work, so it is not required to update free_req in __reclaim_completed_reqs
